### ISSUE TITLE
i open ckan i have mods have shorten mods and im not on 0.24

### ISSUE THREAD

**Issue by thekerbalwow** [KSP-CKAN/CKAN-support#111]
im not on 0.24
![can you fix it](https://cloud.githubusercontent.com/assets/12002830/7213824/3371d20c-e542-11e4-98d0-f7a478052577.PNG)

and i have short of mods

![worst thing ever](https://cloud.githubusercontent.com/assets/12002830/7213831/614b266a-e542-11e4-8483-4496d25e1c1a.PNG)

last time is work fine

last part is im not on 0.24

**Comment by pjf** [comment]
Well, it looks like CKAN certainly thinks you're on 0.24.2!

We try to guess this from looking at the `readme.txt` file in your Kerbal Space Program directory. If it's been overwritten for any reason, we might be picking up the wrong number because of that.

You can *probably* replace your `readme.txt` with just:

```
Version 0.90.0 Beta
```

and it will work fine. (Or better yet, the `readme.txt` that came bundled with your original KSP install.)

**Comment by thekerbalwow** [comment]
folder directory

**Comment by thekerbalwow** [comment]
thanks :+1:

**Comment by Dazpoet** [comment]
Appears resolved to I'll close this, just post again if I misunderstood the situation :)
