### ISSUE TITLE
"All" filter and "New" filter don't work as the name suggests, and a "compatible only" filter should be added.

### ISSUE THREAD

**Issue by Qazerowl** [KSP-CKAN/CKAN-support#121]
Current behaviour:
"All" filter lists only compatible packages. (and it the default filter)
"New in repository" filter lists every package in the repo. This includes incompatible packages. The list of packages displayed by this filter does not change after a "refresh", even if packages are added to the repo in between refreshes.

Expected behaviours:
"All" filter lists every package in the repository (including outdated/incompatible packages), and is not set as the default filter.
"New" filter lists only compatible packages that have been updated or added to the repo since the last client "refresh".
A (new) "Compatible" filter lists all compatible packages, and is the default filter (ie: "Compatible" should be used when ckan is started, and listed at the top of the filter list.)

Specifically, I'm talking about the GUI. I don't use the cli, so I don't know if the filters work properly (or if there are filters at all).

**Comment by KSPjohnFX** [comment]
I would greatly support CKAN having a current list of mods and noting the versions of all the mods changed or introduced on a refresh and enabling the user to sort the mods based on whether they have been updated since the last refresh or added since the last refresh. Currently all mods are displayed if you filter by 'new in repository'

I would suggest some slight changes to the filter menu

'All' would show all mods

'Installed' would show installed mods

'Updated' could show updated installed mods

'New in Repository' could show mods introduced or updated since the last refresh, installed or not.

'Not installed' is mods that are not installed.

a new filter 'compatible' would show all mods in the repository that are compatible, installed or not.

'Incompatible' would show incompatible mods.

'Custom' would have toggles for 'installed', 'updated', 'new', 'compatible', and filter boxes for mod names and author names

I feel this would greatly expand the users ability to find the mods they are looking for.

(also posted in main thread)
