### ISSUE TITLE
Can't update repo

### ISSUE THREAD

**Issue by P2SH** [KSP-CKAN/CKAN-support#123]
Dialog message:
"Failed to connect to repository. Exception: 1 is not a supported code page. Parameter name: codepage"

Win8.1 x64
KSP 1.0

**Comment by Dazpoet** [comment]
What is the output of `ckan repo list` in a terminal?

**Comment by P2SH** [comment]
Listing all known repositories:
  default: 0: https://github.com/KSP-CKAN/CKAN-meta/archive/master.zip

**Comment by Dazpoet** [comment]
That is both what we want to see and most certainly not what I hoped to see since it means there's nothing wrong with your repository listing. 

Could you try just removing it and then re-adding it again to see if the problem persists? If you add another repo like Mechjeb-pre/dev/whatever it's called, and refresh do you get the dev-release in the list?

**Comment by P2SH** [comment]
Also the same message.

**Comment by P2SH** [comment]
Figured it out. The "ICSharpCode.SharpZipLib.Zip.ZipConstants" class in SharpZipLib-ckan_gh221 is outdated. Replaced it with the one from icsharpcode/SharpZipLib and it worked.

**Comment by Dazpoet** [comment]
O_o That's a new one that I never heard off before.

**Comment by pjf** [comment]
We've upgraded SharpZipLib, and that should be visible in the new release coming out today. :)
