### ISSUE TITLE
KSP Version Discrepencies

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN-support#126]
Currently, the latest versions of `KerbalAlarmClock` and `PilotAssistant` are not offered for KSP 1.0.2 installs. I assume this is because these mods have `ksp_version` metadata of `1.0.0`, which they get from AVC .version files, whereas other mods from Kerbal Stuff have a `ksp_version` of `1.0` and are offered.

Presumably the correct thing to do is to have these mods update their .version files to reflect 1.0.2, but that behavior is annoyingly inconsistent with mods from Kerbal Stuff.

The question is, which is the "correct" behavior? With or without the patch number in the KSP version? Then ideally, all mods would follow that behavior.

**Comment by dbent** [comment]
`RasterPropMonitor` is also affected similarly.

**Comment by Dazpoet** [comment]
In a perfect world I'd like to see consistent usage of AVC since that would give mod authors the ability to be very precise. Seeing as subversions hasn't really been happening this fast earlier in KSP history (I think) mod authors will have to adapt.

I've written a short explanation of how CKAN seems to handle the ksp_version field [here](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-6-12-30-Apr-2015?p=1893886&viewfull=1#post1893886) and we're already looking into KAC at https://github.com/KSP-CKAN/NetKAN/issues/1114

**Comment by Dazpoet** [comment]
RPM "fixed" in https://github.com/KSP-CKAN/NetKAN/pull/1122

**Comment by dbent** [comment]
I think all reported mods (`KerbalAlarmClock`, `PilotAssistant`, and `RasterPropMonitor`) are now fixed. Feel free to close or leave open for the fundamental issue.

**Comment by Dazpoet** [comment]
Seems like it, closing this then :)
