### ISSUE TITLE
Cannot uninstall incompatable mods

### ISSUE THREAD

**Issue by yagi-takeru** [KSP-CKAN/CKAN-support#143]
Mods that are incompatible with the current version of KSP cannot be uninstalled through the menu, as the checkbox for installing/uninstalling no longer exists

**Comment by pjf** [comment]
This has been a long-standing bug in the GUI, and definitely needs fixing. :/

You *can* uninstall them using the command-line just fine, but that's more of a workaround rather than a fix.

The latest release (v1.6.15) changes how we manage our mod display under the hood, I don't suppose it helps at all?

**Comment by yagi-takeru** [comment]
not at all, although i think this could probably be fixed with a " if
(installed) {display checkbox;}"
