### ISSUE TITLE
Deprecated mods still in CKAN

### ISSUE THREAD

**Issue by hakan42** [KSP-CKAN/CKAN-support#90]
_From @pastlifeuknow on February 16, 2015 13:40_

Noticed that mods such as Universal storage have mods that are deprecated by according to their description on CKAN but still on CKAN. With the example of US they updated the description to make it clear that it is deprecated. Removal of deprecated mods may be need

_Copied from original issue: KSP-CKAN/CKAN#778_

**Comment by hakan42** [comment]
As CKAN is built right now, we cannot remove addons without breaking the installation of people who have them still installed.

In that case, the client will fail with a HashException, as we had for a long time with the US addon until we introduced the "Deprecated" versions specifically for CKAN.

So, long story short, please do not remove the metadata files before we have a client which can handle deprecations and we are reasonably sure that people have the correct version of the client installed.

**Comment by Dazpoet** [comment]
Would a solution to this problem by any chance also solve the now occuring problem with people getting errors due to updated dependencies?

- https://github.com/KSP-CKAN/CKAN/issues/795
- http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-6-6-26-Mar-2015?p=1809963&viewfull=1#post1809963
