### ISSUE TITLE
Feature request: A way to warn users that an update to a mod is save-breaking

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN-support#99]
Every now and again a mod brings out an update that simply put changes to much to maintain saves using an older version. Using CKAN I often just update whatever needs updating (because it's so easy!) and I must admit I don't always check beforehand what was changed.

I think it would be a good idea if mod metadata could have field which could be set to true if a mod update would break saves using an older version. This would mean that when CKAN attempts to update a mod and finds a "Breaker of saves" : "True" it can warn the user. The field would, I imagine, not do anything when you install a mod for the first time since then it won't be applicable.

I have no Idea how impossible or easy this might be but it sounds like a good idea to me :)

**Comment by pjf** [comment]
+1. This seems like a good idea.

KSP-CKAN/CKAN#211 is a variant of this. There might also be a ticket specifically for breaking saves, but I'm not sure where it is. In any case, the way of doing this would be to specify a minimum version at which the save breaking occurs.

Eg, going from Kerbxample 3 to Kerbxample 4 is save breaking, but from Kerbxample 4 to Kerbxample 4.1 is not. The version 4.x metadata would have a `compatible_to: 4.0` line (or equivalent). If the user's current version is less than the compatibility check, we give them a warning. (And I'd say it *must* have a human displayable warning, because otherwise users are told "this may be save-breaking", but no further details about that.)

Of course, I'd *really* love to see mods check if they've been upgraded from an older version and warn the user with an in-game message. Unfortunately, that's not always a straightforward process. (But it does mean the user gets informed no matter how they upgraded their mods.)

**Comment by Dazpoet** [comment]
A compatible_to keyword sounds like a very good idea to me. However I hope that it would function in a way that it defines a starting point and then all versions after that is also considered compatible or one might end up with a Kerbxample 7 that has to have "compatible_to : 4.0, 5.0, 6.0".

As for the warning keyword that sounds very useful but I don't know if it would work for version problems since you'd end up with Kerbxample having a "warning : Kerbxample" but that might be solvable with a "warning : Kerbxample, max version : <last version that doesn't break saves>".

**Comment by Dazpoet** [comment]
Well well what do you know, I found the original issue about this. https://github.com/KSP-CKAN/CKAN/issues/60
